export class Countries {
  countries: any[] = [
    {name: 'Afghanistan', id: 'Afghanistan', code: 'AF', phone_code: '+93'},
    {name: 'Åland Islands', id: 'Åland Islands', code: 'AX', phone_code: '+358'},
    {name: 'Albania', id: 'Albania', code: 'AL', phone_code: '+355'},
    {name: 'Algeria', id: 'Algeria', code: 'DZ', phone_code: '+213'},
    {name: 'American Samoa', id: 'American Samoa', code: 'AS', phone_code: '+1-684'},
    {name: 'AndorrA', id: 'AndorrA', code: 'AD', phone_code: '+376'},
    {name: 'Angola', id: 'Angola', code: 'AO', phone_code: '+244'},
    {name: 'Anguilla', id: 'Anguilla', code: 'AI', phone_code: '+1-264'},
    {name: 'Antarctica', id: 'Antarctica', code: 'AQ', phone_code: '+672'},
    {name: 'Antigua and Barbuda', id: 'Antigua and Barbuda', code: 'AG', phone_code: '+1-268'},
    {name: 'Argentina', id: 'Argentina', code: 'AR', phone_code: '+54'},
    {name: 'Armenia', id: 'Armenia', code: 'AM', phone_code: '+374'},
    {name: 'Aruba', id: 'Aruba', code: 'AW', phone_code: '+297'},
    {name: 'Australia', id: 'Australia', code: 'AU', phone_code: '+61'},
    {name: 'Austria', id: 'Austria', code: 'AT', phone_code: '+43'},
    {name: 'Azerbaijan', id: 'Azerbaijan', code: 'AZ', phone_code: '+994'},
    {name: 'Bahamas', id: 'Bahamas', code: 'BS', phone_code: '+1-242'},
    {name: 'Bahrain', id: 'Bahrain', code: 'BH', phone_code: '+973'},
    {name: 'Bangladesh', id: 'Bangladesh', code: 'BD', phone_code: '+880'},
    {name: 'Barbados', id: 'Barbados', code: 'BB', phone_code: '+1-246'},
    {name: 'Belarus', id: 'Belarus', code: 'BY', phone_code: '+375'},
    {name: 'Belgium', id: 'Belgium', code: 'BE', phone_code: '+32'},
    {name: 'Belize', id: 'Belize', code: 'BZ', phone_code: '+501'},
    {name: 'Benin', id: 'Benin', code: 'BJ', phone_code: '+229'},
    {name: 'Bermuda', id: 'Bermuda', code: 'BM', phone_code: '+1-441'},
    {name: 'Bhutan', id: 'Bhutan', code: 'BT', phone_code: '+975'},
    {name: 'Bolivia', id: 'Bolivia', code: 'BO', phone_code: '+591'},
    {name: 'Bosnia and Herzegovina', id: 'Bosnia and Herzegovina', code: 'BA', phone_code: '+387'},
    {name: 'Botswana', id: 'Botswana', code: 'BW', phone_code: '+267'},
    {name: 'Bouvet Island', id: 'Bouvet Island', code: 'BV', phone_code: '+47'},
    {name: 'Brazil', id: 'Brazil', code: 'BR', phone_code: '+55'},
    {name: 'British Indian Ocean Territory', id: 'British Indian Ocean Territory', code: 'IO', phone_code: '+246'},
    {name: 'Brunei Darussalam', id: 'Brunei Darussalam', code: 'BN', phone_code: '+673'},
    {name: 'Bulgaria', id: 'Bulgaria', code: 'BG', phone_code: '+359'},
    {name: 'Burkina Faso', id: 'Burkina Faso', code: 'BF', phone_code: '+226'},
    {name: 'Burundi', id: 'Burundi', code: 'BI', phone_code: '+257'},
    {name: 'Cambodia', id: 'Cambodia', code: 'KH', phone_code: '+855'},
    {name: 'Cameroon', id: 'Cameroon', code: 'CM', phone_code: '+237'},
    {name: 'Canada', id: 'Canada', code: 'CA', phone_code: '+1'},
    {name: 'Cape Verde', id: 'Cape Verde', code: 'CV', phone_code: '+238'},
    {name: 'Cayman Islands', id: 'Cayman Islands', code: 'KY', phone_code: '+1-345'},
    {name: 'Central African Republic', id: 'Central African Republic', code: 'CF', phone_code: '+236'},
    {name: 'Chad', id: 'Chad', code: 'TD', phone_code: '+235'},
    {name: 'Chile', id: 'Chile', code: 'CL', phone_code: '+56'},
    {name: 'China', id: 'China', code: 'CN', phone_code: '+86'},
    {name: 'Christmas Island', id: 'Christmas Island', code: 'CX', phone_code: '+61'},
    {name: 'Cocos (Keeling) Islands', id: 'Cocos (Keeling) Islands', code: 'CC', phone_code: '+61'},
    {name: 'Colombia', id: 'Colombia', code: 'CO', phone_code: '+57'},
    {name: 'Comoros', id: 'Comoros', code: 'KM', phone_code: '+269'},
    {name: 'Congo-Brazzaville', id: 'Congo-Brazzaville', code: 'CG', phone_code: '+242'},
    {name: 'Congo-Kinshasa', id: 'Congo-Kinshasa', code: 'CD', phone_code: '+243'},
    {name: 'Cook Islands', id: 'Cook Islands', code: 'CK', phone_code: '+682'},
    {name: 'Costa Rica', id: 'Costa Rica', code: 'CR', phone_code: '+506'},
    {name: 'Côte d\'Ivoire', id: 'Côte d\'Ivoire', code: 'CI', phone_code: '+225'},
    {name: 'Croatia', id: 'Croatia', code: 'HR', phone_code: '+385'},
    {name: 'Cuba', id: 'Cuba', code: 'CU', phone_code: '+53'},
    {name: 'Cyprus', id: 'Cyprus', code: 'CY', phone_code: '+357'},
    {name: 'Czech Republic', id: 'Czech Republic', code: 'CZ', phone_code: '+420'},
    {name: 'Denmark', id: 'Denmark', code: 'DK', phone_code: '+45'},
    {name: 'Djibouti', id: 'Djibouti', code: 'DJ', phone_code: '+253'},
    {name: 'Dominica', id: 'Dominica', code: 'DM', phone_code: '+1-767'},

    {name: 'Dominican Republic', id: 'Dominican Republic', code: 'DO', phone_code: '+1-809'},
    {name: 'Dominican Republic', id: 'Dominican Republic', code: 'DO', phone_code: '+1-829'},
    {name: 'Dominican Republic', id: 'Dominican Republic', code: 'DO', phone_code: '+1-849'},

    {name: 'Ecuador', id: 'Ecuador', code: 'EC', phone_code: '+593'},
    {name: 'Egypt', id: 'Egypt', code: 'EG', phone_code: '+20'},
    {name: 'El Salvador', id: 'El Salvador', code: 'SV', phone_code: '+503'},
    {name: 'Equatorial Guinea', id: 'Equatorial Guinea', code: 'GQ', phone_code: '+240'},
    {name: 'Eritrea', id: 'Eritrea', code: 'ER', phone_code: '+291'},
    {name: 'Estonia', id: 'Estonia', code: 'EE', phone_code: '+372'},
    {name: 'Ethiopia', id: 'Ethiopia', code: 'ET', phone_code: '+251'},
    {name: 'Falkland Islands (Malvinas)', id: 'Falkland Islands (Malvinas)', code: 'FK', phone_code: '+500'},
    {name: 'Faroe Islands', id: 'Faroe Islands', code: 'FO', phone_code: '+298'},
    {name: 'Fiji', id: 'Fiji', code: 'FJ', phone_code: '+679'},
    {name: 'Finland', id: 'Finland', code: 'FI', phone_code: '+358'},
    {name: 'France', id: 'France', code: 'FR', phone_code: '+33'},
    {name: 'French Guiana', id: 'French Guiana', code: 'GF', phone_code: '+594'},
    {name: 'French Polynesia', id: 'French Polynesia', code: 'PF', phone_code: '+689'},
    {name: 'French Southern Territories', id: 'French Southern Territories', code: 'TF', phone_code: '+262'},
    {name: 'Gabon', id: 'Gabon', code: 'GA', phone_code: '+241'},
    {name: 'Gambia', id: 'Gambia', code: 'GM', phone_code: '+220'},
    {name: 'Georgia', id: 'Georgia', code: 'GE', phone_code: '+995'},
    {name: 'Germany', id: 'Germany', code: 'DE', phone_code: '+49'},
    {name: 'Ghana', id: 'Ghana', code: 'GH', phone_code: '+233'},
    {name: 'Gibraltar', id: 'Gibraltar', code: 'GI', phone_code: '+350'},
    {name: 'Greece', id: 'Greece', code: 'GR', phone_code: '+30'},
    {name: 'Greenland', id: 'Greenland', code: 'GL', phone_code: '+299'},
    {name: 'Grenada', id: 'Grenada', code: 'GD', phone_code: '+1-473'},
    {name: 'Guadeloupe', id: 'Guadeloupe', code: 'GP', phone_code: '+590'},
    {name: 'Guam', id: 'Guam', code: 'GU', phone_code: '+1-671'},
    {name: 'Guatemala', id: 'Guatemala', code: 'GT', phone_code: '+502'},
    {name: 'Guernsey', id: 'Guernsey', code: 'GG', phone_code: '+44'},
    {name: 'Guinea', id: 'Guinea', code: 'GN', phone_code: '+224'},
    {name: 'Guinea-Bissau', id: 'Guinea-Bissau', code: 'GW', phone_code: '+245'},
    {name: 'Guyana', id: 'Guyana', code: 'GY', phone_code: '+592'},
    {name: 'Haiti', id: 'Haiti', code: 'HT', phone_code: '+509'},
    {
      name: 'Heard Island and Mcdonald Islands',
      id: 'Heard Island and Mcdonald Islands',
      code: 'HM',
      phone_code: '+672'
    },
    {name: 'Holy See (Vatican City State)', id: 'Holy See (Vatican City State)', code: 'VA', phone_code: '+379'},
    {name: 'Honduras', id: 'Honduras', code: 'HN', phone_code: '+504'},
    {name: 'Hong Kong', id: 'Hong Kong', code: 'HK', phone_code: '+852'},
    {name: 'Hungary', id: 'Hungary', code: 'HU', phone_code: '+36'},
    {name: 'Iceland', id: 'Iceland', code: 'IS', phone_code: '+354'},
    {name: 'India', id: 'India', code: 'IN', phone_code: '+91'},
    {name: 'Indonesia', id: 'Indonesia', code: 'ID', phone_code: '+62'},
    {name: 'Iran, Islamic Republic of', id: 'Iran, Islamic Republic of', code: 'IR', phone_code: '+98'},
    {name: 'Iraq', id: 'Iraq', code: 'IQ', phone_code: '+964'},
    {name: 'Ireland', id: 'Ireland', code: 'IE', phone_code: '+353'},
    {name: 'Isle of Man', id: 'Isle of Man', code: 'IM', phone_code: '+44'},
    {name: 'Israel', id: 'Israel', code: 'IL', phone_code: '+972'},
    {name: 'Italy', id: 'Italy', code: 'IT', phone_code: '+39'},
    {name: 'Jamaica', id: 'Jamaica', code: 'JM', phone_code: '+1-876'},
    {name: 'Japan', id: 'Japan', code: 'JP', phone_code: '+81'},
    {name: 'Jersey', id: 'Jersey', code: 'JE', phone_code: '+44'},
    {name: 'Jordan', id: 'Jordan', code: 'JO', phone_code: '+962'},
    {name: 'Kazakhstan', id: 'Kazakhstan', code: 'KZ', phone_code: '+7'},
    {name: 'Kenya', id: 'Kenya', code: 'KE', phone_code: '+254'},
    {name: 'Kiribati', id: 'Kiribati', code: 'KI', phone_code: '+686'},
    {
      name: 'Korea, Democratic People\'s Republic of',
      id: 'Korea, Democratic People\'s Republic of',
      code: 'KP',
      phone_code: '+850'
    },
    {name: 'Korea, Republic of', id: 'Korea, Republic of', code: 'KR', phone_code: '+82'},
    {name: 'Kuwait', id: 'Kuwait', code: 'KW', phone_code: '+965'},
    {name: 'Kyrgyzstan', id: 'Kyrgyzstan', code: 'KG', phone_code: '+996'},
    {
      name: 'Lao People\'s Democratic Republic',
      id: 'Lao People\'s Democratic Republic',
      code: 'LA',
      phone_code: '+856'
    },
    {name: 'Latvia', id: 'Latvia', code: 'LV', phone_code: '+371'},
    {name: 'Lebanon', id: 'Lebanon', code: 'LB', phone_code: '+961'},
    {name: 'Lesotho', id: 'Lesotho', code: 'LS', phone_code: '+266'},
    {name: 'Liberia', id: 'Liberia', code: 'LR', phone_code: '+231'},
    {name: 'Libyan Arab Jamahiriya', id: 'Libyan Arab Jamahiriya', code: 'LY', phone_code: '+218'},
    {name: 'Liechtenstein', id: 'Liechtenstein', code: 'LI', phone_code: '+423'},
    {name: 'Lithuania', id: 'Lithuania', code: 'LT', phone_code: '+370'},
    {name: 'Luxembourg', id: 'Luxembourg', code: 'LU', phone_code: '+352'},
    {name: 'Macao', id: 'Macao', code: 'MO', phone_code: '+853'},
    {
      name: 'Macedonia, the Former Yugoslav Republic of',
      id: 'Macedonia, the Former Yugoslav Republic of',
      code: 'MK',
      phone_code: '+389'
    },
    {name: 'Madagascar', id: 'Madagascar', code: 'MG', phone_code: '+261'},
    {name: 'Malawi', id: 'Malawi', code: 'MW', phone_code: '+265'},
    {name: 'Malaysia', id: 'Malaysia', code: 'MY', phone_code: '+60'},
    {name: 'Maldives', id: 'Maldives', code: 'MV', phone_code: '+960'},
    {name: 'Mali', id: 'Mali', code: 'ML', phone_code: '+223'},
    {name: 'Malta', id: 'Malta', code: 'MT', phone_code: '+356'},
    {name: 'Marshall Islands', id: 'Marshall Islands', code: 'MH', phone_code: '+692'},
    {name: 'Martinique', id: 'Martinique', code: 'MQ', phone_code: '+596'},
    {name: 'Mauritania', id: 'Mauritania', code: 'MR', phone_code: '+222'},
    {name: 'Mauritius', id: 'Mauritius', code: 'MU', phone_code: '+230'},
    {name: 'Mayotte', id: 'Mayotte', code: 'YT', phone_code: '+262'},
    {name: 'Mexico', id: 'Mexico', code: 'MX', phone_code: '+52'},
    {name: 'Micronesia, Federated States of', id: 'Micronesia, Federated States of', code: 'FM', phone_code: '+691'},
    {name: 'Moldova, Republic of', id: 'Moldova, Republic of', code: 'MD', phone_code: '+373'},
    {name: 'Monaco', id: 'Monaco', code: 'MC', phone_code: '+377'},
    {name: 'Mongolia', id: 'Mongolia', code: 'MN', phone_code: '+976'},
    {name: 'Montenegro', id: 'Montenegro', code: 'ME', phone_code: '+382'},
    {name: 'Montserrat', id: 'Montserrat', code: 'MS', phone_code: '+1-664'},
    {name: 'Morocco', id: 'Morocco', code: 'MA', phone_code: '+212'},
    {name: 'Mozambique', id: 'Mozambique', code: 'MZ', phone_code: '+258'},
    {name: 'Myanmar', id: 'Myanmar', code: 'MM', phone_code: '+95'},
    {name: 'Namibia', id: 'Namibia', code: 'NA', phone_code: '+264'},
    {name: 'Nauru', id: 'Nauru', code: 'NR', phone_code: '+674'},
    {name: 'Nepal', id: 'Nepal', code: 'NP', phone_code: '+977'},
    {name: 'Netherlands', id: 'Netherlands', code: 'NL', phone_code: '+31'},
    {name: 'Netherlands Antilles', id: 'Netherlands Antilles', code: 'AN', phone_code: '+599'},
    {name: 'New Caledonia', id: 'New Caledonia', code: 'NC', phone_code: '+687'},
    {name: 'New Zealand', id: 'New Zealand', code: 'NZ', phone_code: '+64'},
    {name: 'Nicaragua', id: 'Nicaragua', code: 'NI', phone_code: '+505'},
    {name: 'Niger', id: 'Niger', code: 'NE', phone_code: '+227'},
    {name: 'Nigeria', id: 'Nigeria', code: 'NG', phone_code: '+234'},
    {name: 'Niue', id: 'Niue', code: 'NU', phone_code: '+683'},
    {name: 'Norfolk Island', id: 'Norfolk Island', code: 'NF', phone_code: '+672'},
    {name: 'Northern Mariana Islands', id: 'Northern Mariana Islands', code: 'MP', phone_code: '+1-670'},
    {name: 'Norway', id: 'Norway', code: 'NO', phone_code: '+47'},
    {name: 'Oman', id: 'Oman', code: 'OM', phone_code: '+968'},
    {name: 'Pakistan', id: 'Pakistan', code: 'PK', phone_code: '+92'},
    {name: 'Palau', id: 'Palau', code: 'PW', phone_code: '+680'},
    {name: 'Palestinian Territory, Occupied', id: 'Palestinian Territory, Occupied', code: 'PS', phone_code: '+970'},
    {name: 'Panama', id: 'Panama', code: 'PA', phone_code: '+507'},
    {name: 'Papua New Guinea', id: 'Papua New Guinea', code: 'PG', phone_code: '+675'},
    {name: 'Paraguay', id: 'Paraguay', code: 'PY', phone_code: '+595'},
    {name: 'Peru', id: 'Peru', code: 'PE', phone_code: '+51'},
    {name: 'Philippines', id: 'Philippines', code: 'PH', phone_code: '+63'},
    {name: 'Pitcairn', id: 'Pitcairn', code: 'PN', phone_code: '+872'},
    {name: 'Poland', id: 'Poland', code: 'PL', phone_code: '+48'},
    {name: 'Portugal', id: 'Portugal', code: 'PT', phone_code: '+351'},
    {name: 'Puerto Rico', id: 'Puerto Rico', code: 'PR', phone_code: '+1-787, +1-939'},
    {name: 'Qatar', id: 'Qatar', code: 'QA', phone_code: '+974'},
    {name: 'Reunion', id: 'Reunion', code: 'RE', phone_code: '+262'},
    {name: 'Romania', id: 'Romania', code: 'RO', phone_code: '+40'},
    {name: 'Russian Federation', id: 'Russian Federation', code: 'RU', phone_code: '+7'},
    {name: 'Rwanda', id: 'Rwanda', code: 'RW', phone_code: '+250'},
    {name: 'Saint Helena', id: 'Saint Helena', code: 'SH', phone_code: '+290'},
    {name: 'Saint Kitts and Nevis', id: 'Saint Kitts and Nevis', code: 'KN', phone_code: '+1-869'},
    {name: 'Saint Lucia', id: 'Saint Lucia', code: 'LC', phone_code: '+1-758'},
    {name: 'Saint Pierre and Miquelon', id: 'Saint Pierre and Miquelon', code: 'PM', phone_code: '+508'},
    {
      name: 'Saint Vincent and the Grenadines',
      id: 'Saint Vincent and the Grenadines',
      code: 'VC',
      phone_code: '+1-784'
    },
    {name: 'Samoa', id: 'Samoa', code: 'WS', phone_code: '+685'},
    {name: 'San Marino', id: 'San Marino', code: 'SM', phone_code: '+378'},
    {name: 'Sao Tome and Principe', id: 'Sao Tome and Principe', code: 'ST', phone_code: '+239'},
    {name: 'Saudi Arabia', id: 'Saudi Arabia', code: 'SA', phone_code: '+966'},
    {name: 'Senegal', id: 'Senegal', code: 'SN', phone_code: '+221'},
    {name: 'Serbia', id: 'Serbia', code: 'RS', phone_code: '+381'},
    {name: 'Seychelles', id: 'Seychelles', code: 'SC', phone_code: '+248'},
    {name: 'Sierra Leone', id: 'Sierra Leone', code: 'SL', phone_code: '+232'},
    {name: 'Singapore', id: 'Singapore', code: 'SG', phone_code: '+65'},
    {name: 'Slovakia', id: 'Slovakia', code: 'SK', phone_code: '+421'},
    {name: 'Slovenia', id: 'Slovenia', code: 'SI', phone_code: '+386'},
    {name: 'Solomon Islands', id: 'Solomon Islands', code: 'SB', phone_code: '+677'},
    {name: 'Somalia', id: 'Somalia', code: 'SO', phone_code: '+252'},
    {name: 'South Africa', id: 'South Africa', code: 'ZA', phone_code: '+27'},
    {
      name: 'South Georgia and the South Sandwich Islands',
      id: 'South Georgia and the South Sandwich Islands',
      code: 'GS',
      phone_code: '+500'
    },
    {name: 'Spain', id: 'Spain', code: 'ES', phone_code: '+34'},
    {name: 'Sri Lanka', id: 'Sri Lanka', code: 'LK', phone_code: '+94'},
    {name: 'Sudan', id: 'Sudan', code: 'SD', phone_code: '+249'},
    {name: 'Suriname', id: 'Suriname', code: 'SR', phone_code: '+597'},
    {name: 'Svalbard and Jan Mayen', id: 'Svalbard and Jan Mayen', code: 'SJ', phone_code: '+47'},
    {name: 'Swaziland', id: 'Swaziland', code: 'SZ', phone_code: '+268'},
    {name: 'Sweden', id: 'Sweden', code: 'SE', phone_code: '+46'},
    {name: 'Switzerland', id: 'Switzerland', code: 'CH', phone_code: '+41'},
    {name: 'Syrian Arab Republic', id: 'Syrian Arab Republic', code: 'SY', phone_code: '+963'},
    {name: 'Taiwan, Province of China', id: 'Taiwan, Province of China', code: 'TW', phone_code: '+886'},
    {name: 'Tajikistan', id: 'Tajikistan', code: 'TJ', phone_code: '+992'},
    {name: 'Tanzania', id: 'Tanzania', code: 'TZ', phone_code: '+255'},
    {name: 'Thailand', id: 'Thailand', code: 'TH', phone_code: '+66'},
    {name: 'Timor-Leste', id: 'Timor-Leste', code: 'TL', phone_code: '+670'},
    {name: 'Togo', id: 'Togo', code: 'TG', phone_code: '+228'},
    {name: 'Tokelau', id: 'Tokelau', code: 'TK', phone_code: '+690'},
    {name: 'Tonga', id: 'Tonga', code: 'TO', phone_code: '+676'},
    {name: 'Trinidad and Tobago', id: 'Trinidad and Tobago', code: 'TT', phone_code: '+1-868'},
    {name: 'Tunisia', id: 'Tunisia', code: 'TN', phone_code: '+216'},
    {name: 'Turkey', id: 'Turkey', code: 'TR', phone_code: '+90'},
    {name: 'Turkmenistan', id: 'Turkmenistan', code: 'TM', phone_code: '+993'},
    {name: 'Turks and Caicos Islands', id: 'Turks and Caicos Islands', code: 'TC', phone_code: '+1-649'},
    {name: 'Tuvalu', id: 'Tuvalu', code: 'TV', phone_code: '+688'},
    {name: 'Uganda', id: 'Uganda', code: 'UG', phone_code: '+256'},
    {name: 'Ukraine', id: 'Ukraine', code: 'UA', phone_code: '+380'},
    {name: 'United Arab Emirates', id: 'United Arab Emirates', code: 'AE', phone_code: '+971'},
    {name: 'United Kingdom', id: 'United Kingdom', code: 'GB', phone_code: '+44'},
    {name: 'United States', id: 'United States', code: 'US', phone_code: '+1'},
    {
      name: 'United States Minor Outlying Islands',
      id: 'United States Minor Outlying Islands',
      code: 'UM',
      phone_code: '+1'
    },
    {name: 'Uruguay', id: 'Uruguay', code: 'UY', phone_code: '+598'},
    {name: 'Uzbekistan', id: 'Uzbekistan', code: 'UZ', phone_code: '+998'},
    {name: 'Vanuatu', id: 'Vanuatu', code: 'VU', phone_code: '+678'},
    {name: 'Venezuela', id: 'Venezuela', code: 'VE', phone_code: '+58'},
    {name: 'Viet Nam', id: 'Viet Nam', code: 'VN', phone_code: '+84'},
    {name: 'Virgin Islands, British', id: 'Virgin Islands, British', code: 'VG', phone_code: '+1-284'},
    {name: 'Virgin Islands, U.S.', id: 'Virgin Islands, U.S.', code: 'VI', phone_code: '+1-340'},
    {name: 'Wallis and Futuna', id: 'Wallis and Futuna', code: 'WF', phone_code: '+681'},
    {name: 'Western Sahara', id: 'Western Sahara', code: 'EH', phone_code: '+212'},
    {name: 'Yemen', id: 'Yemen', code: 'YE', phone_code: '+967'},
    {name: 'Zambia', id: 'Zambia', code: 'ZM', phone_code: '+260'},
    {name: 'Zimbabwe', id: 'Zimbabwe', code: 'ZW', phone_code: '+263'}
  ]
}

